[package]
name = "nbsh"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.45"
async-process = "1.2.0"
async-std = "1.10.0"
futures = "0.3.17"
libc = "0.2.107"
nix = "0.23.0"
pty-process = { version = "0.1.0", features = ["backend-async-std"] }
textmode = { version = "0.1.0", features = ["async"] }
vt100 = "0.12.0"

[features]
