targets = [
    { triple = "x86_64-unknown-linux-musl" },
    { triple = "x86_64-unknown-linux-gnu" },
]

[advisories]
yanked = "deny"
unsound = "deny"

[bans]

[licenses]
allow = ["MIT", "Apache-2.0"]
copyleft = "deny"
